version: 2

jobs:
  ruby-2.5:
    docker:
      - image: rubylang/ruby:2.5.7-bionic
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rake
  ruby-2.6:
    docker:
      - image: rubylang/ruby:2.6.5-bionic
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rake

  ruby-2.7:
    docker:
      - image: rubylang/ruby:2.7.0-bionic
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - ruby-2.5
      - ruby-2.6
      - ruby-2.7
