version: 2

jobs:
  ruby-2.5:
    docker:
      - image: ruby:2.5.7
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rake
  ruby-2.6:
    docker:
      - image: ruby:2.6.5
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - ruby-2.5
      - ruby-2.6
