name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        # https://hub.docker.com/r/rubylang/ruby
        - '2.5-bionic'
        - '2.6-bionic'
        - '2.7-bionic'
        - '3.0.0-preview2-bionic'
        - 'latest'
    container:
      image: rubylang/ruby:${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: |
          gem install bundler -v 2.2.0 --force
          bundle install
          bundle exec rubocop
          bundle exec rake
