name: Ruby

on: [push]

jobs:
  ruby25:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test
      run: |
        gem install bundler -v 2.1.2
        bundle install
        bundle exec rubocop
        bundle exec rake

  ruby26:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test
      run: |
        gem install bundler -v 2.1.2
        bundle install
        bundle exec rubocop
        bundle exec rake

  ruby27:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test
      run: |
        gem install bundler -v 2.1.2
        bundle install
        bundle exec rubocop
        bundle exec rake
